enanomapper-dev.owl, internal/iao-ext.owl
@JKChang2015 and/or @G-Owen how does this look?
=> A 'statistical algorithm' term

internal/npo-ext.owl
Please check if the ENM_00xxxxxx codes are OK.
=> Added more JRC representational test materials

enanomapper-dev.owl
@laurent2207, @thomasexner, how does this look?
=> Updated acks

enanomapper-dev.owl
#191  NanoinformaTIX acknowledgement
=> NanoinformaTIX acknowledgement

config/ncit.iris
https://github.com/enanomapper/ontologies/issues/306
@egonw
=> Added "Diesel Exhaust Particulate" term

config/ncit.iris
#https://github.com/enanomapper/ontologies/issues/308
@egonw , I have updated the superclass link for this addition.
=> Added adsorption with BFO superclass

internal-dev/pato-ext.owl
https://github.com/enanomapper/ontologies/issues/234
@egonw
=> Moved dissolution rate from CHEMINF to PATO

internal/npo-ext.owl
=> Added term JRCNM40011a

config/chmo.iris
Fixes #329 
(issue #310 was closed before adding the term to  chmo.iris)
=> Fixes #310 #329

config/ncit.iris
=> Added Milligram per Kilogram per Day

config/ncit.iris
=> Addeds kg/m3

internal/bao-ext.owl
solves #298 (more description of the differences in the issue)
=> Updated with WST-1 and 8 assays

internal/bao-ext.owl
solves #305
Unsure about which definition from the harmonizer to use
=> Added SDS-PAGE assay from NSC-Terminology

enanomapper.owl, internal/ncit/ncit-ext.owl
Subclass of http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C119826 (exposure method)
=> Added term: pulmonary instillation

config/bao.iris
=> Added PAGE

scripts/src/tests/assets/test_entities.sparql, scripts/src/tests/assets/test_root.sparql, scripts/src/tests/test_root_classes.py
Added new SPARQL query to detect the issue described in #366 where adding a class at the root (e.g., because it is included in an owl:subClassOf axiom without being present in any module) goes unnoticed
=> Solves #366

.github/workflows/slim-ontologies.yml
New slimming step using the msio config files
=> Added msio

.github/workflows/build.yml, config/uberon.iris, external-dev/bao-slim.owl, external-dev/bfo-slim.owl, external-dev/bto-slim.owl, external-dev/ccont-slim.owl, external-dev/cheminf-slim.owl, external-dev/chmo-slim.owl, external-dev/clo-slim.owl, external-dev/envo-slim.owl, external-dev/fabio-slim.owl, external-dev/go-slim.owl, external-dev/iao-slim.owl, external-dev/msio-slim.owl, external-dev/npo-slim.owl, external-dev/obcs-slim.owl, external-dev/obi-slim.owl, external-dev/pato-slim.owl, external-dev/sio-slim.owl, external-dev/uberon-slim.owl, external-dev/uo-slim.owl, scripts/src/tests/assets/test_entities.sparql
Anatomical entity is a material entity  (BFO_0000040) @egonw
Until now, it was under entity, at the root of the ontology.
=> Changed subsumption of anatomical entity

internal-dev/npo-ext.owl
Aerogel is defined by https://goldbook.iupac.org/terms/view/A00173 as: Gel comprised of a microporous solid in which the dispersed phase is a gas.
Filed under nanostructured material and not gel, as gels have by definition a liquid dispersed phase. 
Do you agree @vedina?
=> Added aerogel

.github/workflows/build.yml, config/chebi.iris, external-dev/bao-slim.owl, external-dev/bfo-slim.owl, external-dev/bto-slim.owl, external-dev/ccont-slim.owl, external-dev/cheminf-slim.owl, external-dev/chmo-slim.owl, external-dev/clo-slim.owl, external-dev/envo-slim.owl, external-dev/fabio-slim.owl, external-dev/go-slim.owl, external-dev/iao-slim.owl, external-dev/msio-slim.owl, external-dev/npo-slim.owl, external-dev/obcs-slim.owl, external-dev/obi-slim.owl, external-dev/pato-slim.owl, external-dev/sio-slim.owl, external-dev/uberon-slim.owl, external-dev/uo-slim.owl, internal-dev/chebi-ext.owl
Starting PR to add Aluminosilicate to slims
=> Added aluminosilicate to slims

internal-dev/chebi-ext.owl
=> Added rutile, anatase

config/ncit.iris
=> Added nanocomposite as subclass of nanomaterial

.github/workflows/term-request.yml, scripts/src/generate_iri.sh
Label 'term request' will trigger a workflow to assign a free internal ENM IRI.
=> Suggest IRIs upon term request

internal-dev/cheminf-ext.owl
=> added steric hindrance

config/go.iris
=> Added g1/s arrest process

config/go.iris
=> Added GO biological processes

internal-dev/npo-ext.owl
As a subClassOf `microscopic synthesis part`, like agglomeration, aggregation, dispersion, etc.
=> Added ion leakage

.github/workflows/build.yml, config/go.iris
As a subClassOf cellular process
=> Added autophagy

internal-dev/cheminf-ext.owl
as a subClassOf `chemical substance quality` (it applies to the bulk, not molecule)
=> Added oxygen vacancies

config/go.iris
subClassOf `positive regulation of biological process`
=> Added caspase upregulation

internal-dev/npo-ext.owl
subClassOf functionalization of np
=> Added amino-functionalization of np

enanomapper-dev.owl, internal-dev/go-ext.owl
subclass of `catalytic activity`
=> Added module and term Cathepsin activity

config/go.iris
=> Import across plasma membrane

config/go.iris
=> Added calcium import

config/go.iris
=> Term additions for SbD4Nano

config/npo.iris
Right now `hydrodynamic size` is right below `quality`.
=> Hydrodynamic size is a subClassOf size

internal-dev/obi-ext.owl
Added the last missing assay for the list in #558
=> BAL assay with endpoint cell counts solves #620

config/efo.iris, config/ncit.iris, config/sio.iris, enanomapper-dev.owl, internal-dev/efo-ext.owl, internal-dev/ncit-ext.owl
Several term additions + #673 (Add organisms from which cell lines are derived)
=> Batch adding organisms and cell lines needed for the Causal links network (SbD4Nano)

.github/workflows/build.yml, config/bao-term-file.txt, config/bto.iris, config/clo.iris, config/ncit.iris, external-dev/aopo-slim.owl, external-dev/bao-slim.owl, external-dev/bfo-slim.owl, external-dev/bto-slim.owl, external-dev/ccont-slim.owl, external-dev/chebi-slim.owl, external-dev/cheminf-slim.owl, external-dev/chmo-slim.owl, external-dev/clo-slim.owl, external-dev/envo-slim.owl, external-dev/fabio-slim.owl, external-dev/go-slim.owl, external-dev/iao-slim.owl, external-dev/msio-slim.owl, external-dev/ncit-slim.owl, external-dev/npo-slim.owl, external-dev/obcs-slim.owl, external-dev/obi-slim.owl, external-dev/pato-slim.owl, external-dev/sio-slim.owl, external-dev/uberon-slim.owl, external-dev/uo-slim.owl, internal-dev/efo-ext.owl, internal-dev/ncit-ext.owl, scripts/src/build-workflow/props.sh
=> Batch adding cells for SbD4Nano

enanomapper-dev.owl, internal-dev/nmlco.owl
Creates a version of the Nanomaterial Lifecycle Ontology (nmlco) with environmental fate as a stage
=> Create nmlco.owl, added environmental fate

internal-dev/npo-ext.owl
=> Added c-c and carboxy function.

config/chebi.iris, config/ncit.iris, external-dev/aopo-slim.owl, external-dev/bao-slim.owl, external-dev/bfo-slim.owl, external-dev/bto-slim.owl, external-dev/ccont-slim.owl, external-dev/chebi-slim.owl, external-dev/cheminf-slim.owl, external-dev/chmo-slim.owl, external-dev/clo-slim.owl, external-dev/envo-slim.owl, external-dev/fabio-slim.owl, external-dev/go-slim.owl, external-dev/iao-slim.owl, external-dev/msio-slim.owl, external-dev/ncit-slim.owl, external-dev/npo-slim.owl, external-dev/obcs-slim.owl, external-dev/obi-slim.owl, external-dev/pato-slim.owl, external-dev/sio-slim.owl, external-dev/uberon-slim.owl, external-dev/uo-slim.owl, internal-dev/chemicals_materials.owl
=> Chemical compositions
